/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hoge' at '16/04/02 1:03' with Gradle 2.9
 *
 * @author hoge, @date 16/04/02 1:03
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
